title: Nicks.TV Status Page
baseURL: 'https://status.nicks.tv'
languageCode: en
params:
  copyrightHolder: Nicks.TV
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit
    https://github.com/weeblrpress/clearstatus'
    href='https://github.com/weeblrpress/clearstatus'>ClearStatus Page Link</a>
    provides an how to on how to make such an awesome status page.
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit nicks.tv'
    href='https://nicks.tv/'></a> systems operations.<br />or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  groups:
    - Hosting
    - Media
  logo: /images/nick.tv_banner_50_percent.jpg
  meta_description: >-
    This status page provides updated information about our systems normal
    operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: ''
      name: Media
    - description: ''
      link: 'https://nicks.website/'
      name: Hosting
  timezoneString: ' America/New_York'
