title: Nicks.TV Status Page
baseURL: 'https://status.nicks.tv'
languageCode: en
params:
  copyrightHolder: Nicks.TV
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit
    https://github.com/weeblrpress/clearstatus'
    href='https://github.com/weeblrpress/clearstatus'>ClearStatus Page Link</a>
    provides an how to on how to make such an awesome status page.
  description_header: "Information about <a class='text-grey-darkest' title='Visit nicks.tv' href='https://nicks.tv/'></a> systems operations.<br />or subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new events.\n\n\t\t\t\t\n<!-- Start Open Web Analytics Tracker -->\n<script type=\"text/javascript\">\n//<![CDATA[\nvar owa_baseUrl = 'https://analytics.nicks.website/';\nvar owa_cmds = owa_cmds || [];\nowa_cmds.push(['setSiteId', 'f7e386dc9d422fc1c24706aa97099167']);\nowa_cmds.push(['trackPageView']);\nowa_cmds.push(['trackClicks']);\nowa_cmds.push(['trackDomStream']);\n\n(function() {\n\tvar _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;\n\towa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );\n\t_owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';\n\tvar _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);\n}());\n//]]>\n</script>\n<!-- End Open Web Analytics Code -->\n\n<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->\n<script>\n(function(f, a, t, h, o, m){\n\ta[h]=a[h]||function(){\n\t\t(a[h].q=a[h].q||[]).push(arguments)\n\t};\n\to=f.createElement('script'),\n\tm=f.getElementsByTagName('script')[0];\n\to.async=1; o.src=t; o.id='fathom-script';\n\tm.parentNode.insertBefore(o,m)\n})(document, window, '//ft.nicks.website/tracker.js', 'fathom');\nfathom('set', 'siteId', 'CSCJS');\nfathom('trackPageview');\n</script>\n<!-- / Fathom -->\t\t\n\n<script type=\"text/javascript\">\nvar LHCChatOptions = {};\nLHCChatOptions.opt = {widget_height:340,widget_width:300,popup_height:520,popup_width:500,domain:'status.nicks.tv'};\n(function() {\nvar po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;\nvar referrer = (document.referrer) ? encodeURIComponent(document.referrer.substr(document.referrer.indexOf('://')+1)) : '';\nvar location  = (document.location) ? encodeURIComponent(window.location.href.substring(window.location.protocol.length)) : '';\npo.src = 'https://livechat.nicks.website/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/1?r='+referrer+'&l='+location;\nvar s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);\n})();\n</script>"
  eventsPerPage: 10
  groups:
    - Hosting
    - Media
  logo: /images/nick.tv_banner_50_percent.jpg
  meta_description: >-
    This status page provides updated information about our systems normal
    operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 | Jan 2 2006'
  systems:
    - description: ''
      group: Hosting
      link: 'https://nicks.website/'
      name: Web Hosting
    - group: Hosting
      link: 'https://allofthe.email'
      name: eMail
    - group: Media
      name: Plex
    - group: Media
      name: JellyFin
    - group: Media
      name: Requests
  timezoneString: ' America/New_York'
